apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zuul
  template:
    metadata:
      labels:
        component: zuul
    spec:
      containers:
      - env:
        - name: SPRING_EUREKA
          value: http://eureka-cluster-ip-service:8761/eureka
        image: asia.gcr.io/selforder-1553324212477/zull-server:1.0.1
        name: zuul
        ports:
        - containerPort: 8760
