apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: batchjob
spec:
  replicas: 1
  selector:
    matchLabels:
      component: batchjob
  template:
    metadata:
      labels:
        component: batchjob
    spec:
      containers:
      - env:
        - name: SPRING_EUREKA
          value: http://eureka-cluster-ip-service:8761/eureka
        image: asia.gcr.io/selforder-1553324212477/batchjobservice:1.3.3
        name: batchjob
        ports:
        - containerPort: 80